theme: jekyll-theme-minimal
title: Learning
description: Doing this for fun.
github.is_project_page: false
is_project_page: false
logo: https://avatars3.githubusercontent.com/u/39960794?s=460&v=4
show_downloads: true
